import { OnInit } from "@angular/core";
import { ControlValueAccessor } from "@angular/forms";
import { FormInputBase } from "../baseclass/form.base.class";
export declare const CUSTOM_TEXT_AREA_INPUT_CONTROL_VALUE_ACCESSOR: any;
export declare const BASE_IMPL_TEXTAREA_INPUT: any;
export declare class TextAreaComponent extends FormInputBase implements OnInit, ControlValueAccessor {
    fieldLabel: string;
    fieldName: string;
    allowBlank: string;
    errorMsg: string;
    disabled: boolean;
    noOfrows: number;
    noOfCols: number;
    placeholder: string;
    iconFeedBack: boolean;
    fontStyle: string;
    fontFamily: string;
    fontSize: string;
    fieldIcon: string;
    hasLabel: boolean;
    pattern: string;
    elementId: string;
    spanId: string;
    iconName: string;
    helpInfoMsg: string;
    isValid: boolean;
    divCss: string;
    iconClassName: string;
    fieldglyphIcon: string;
    regEx: RegExp;
    constructor();
    ngOnInit(): void;
    private innerValue;
    private onTouchedCallback;
    private onChangeCallback;
    value: any;
    onBlur(): void;
    writeValue(value: any): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    validate(): void;
    isValidInput(): boolean;
    setValidClassNames(): void;
    setInvalidatedClassNames(): void;
}
